apiVersion: v1
kind: Service
metadata:
  namespace: aib2b
  name: redis-cluster-svc-aib2b
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 30379
    - name: cluster
      port: 16379
      targetPort: 16379
      protocol: TCP
      nodePort: 30378
  selector:
    app: redis
